### ISSUE TITLE
Allow to use Gitlab CI instead of Jenkins

### ISSUE THREAD

**Issue by BR0kEN-** [BR0kEN-/cikit#114]
## Todo

- [ ] Ask on CI droplet's provisioning what CI strategy to use: own Jenkins instance or Gitlab CI.
- [ ] Add a role for installing [Gitlab Runner](https://docs.gitlab.com/runner/install/linux-repository.html).
- [ ] Update the documentation.
- [ ] Add the changelog record.

Thanks @boyanborisov for the inspiration.
